# URL limpa apenas com o endereço do servidor
spring.datasource.url=jdbc:postgresql://ep-silent-hall-ano3tupx-pooler.c-6.us-east-1.aws.neon.tech/DevLog?sslmode=require

# Usuário e Senha separados
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5NdUZYs3TGuL

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true